// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA446butcI6UGzDpLklLJ1eHMKj1XhXj40',
    appId: '1:721603480232:web:2e357091fc5f2d7f07d09d',
    messagingSenderId: '721603480232',
    projectId: 'fir-notification-99758',
    authDomain: 'fir-notification-99758.firebaseapp.com',
    storageBucket: 'fir-notification-99758.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcu0QCPLeKXHXjyqW8PpKUHL9LtV38hgI',
    appId: '1:721603480232:android:e3c12317907c328107d09d',
    messagingSenderId: '721603480232',
    projectId: 'fir-notification-99758',
    storageBucket: 'fir-notification-99758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYunjD8OshtH-2V9FcxDb7zH8Lhp7TsBw',
    appId: '1:721603480232:ios:57ff8eb6bafc17f207d09d',
    messagingSenderId: '721603480232',
    projectId: 'fir-notification-99758',
    storageBucket: 'fir-notification-99758.appspot.com',
    iosClientId:
        '721603480232-pgigabc8uvpormvv0a85srmorutj4232.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYunjD8OshtH-2V9FcxDb7zH8Lhp7TsBw',
    appId: '1:721603480232:ios:57ff8eb6bafc17f207d09d',
    messagingSenderId: '721603480232',
    projectId: 'fir-notification-99758',
    storageBucket: 'fir-notification-99758.appspot.com',
    iosClientId:
        '721603480232-pgigabc8uvpormvv0a85srmorutj4232.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
